# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donutapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='word_id',
            new_name='word',
        ),
    ]
